# Generated by Django 5.0.4 on 2024-05-27 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ptype',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.producttype'),
        ),
    ]
